os: linux
dist: xenial
git:
  depth: 1
language: go
go: "1.11.4"
jobs:
  include:
    - script: ./mage -v test
    - stage: "QA"
      name: "Linting"
      script: ./mage -v lint
    - name: "Test coverage"
      script: ./mage -v coverage:default
    - name: "Benckmarks"
      script: ./mage -v benchmark
    - stage: "Deploy"
      script: ./mage -v build
after_success:
  - bash <(curl -s https://codecov.io/bash)

