[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/blevesearch/bleve"
  version = "0.7.0"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  version = "1.5.3"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.1.1"

[[constraint]]
  name = "github.com/ntrrg/ntgo"
  branch = "master"
