[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/blevesearch/bleve"
  version = "0.7.0"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  version = "1.5.3"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.1.2"

[[constraint]]
  name = "github.com/ntrrg/ntgo"
  branch = "master"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "e3636079e1a4c1f337f212cc5cd2aca108f6c900"
